import{a as h,S as g,i as s}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const S="44094007-67477d06fc63ea0136e02e71a",L="https://pixabay.com/api/";async function c(r,o){try{return(await h.get(L,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:"15"}})).data}catch(t){throw console.error("Error fetching images:",t),t}}function u(r){const o=document.querySelector(".galleriesBox"),t=r.map(e=>`
      <a class="gallery-item" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${e.likes}</p>
          <p class="info-item"><span>Views:</span> ${e.views}</p>
          <p class="info-item"><span>Comments:</span> ${e.comments}</p>
          <p class="info-item"><span>Downloads:</span> ${e.downloads}</p>
        </div>
      </a>`).join("");o.innerHTML=t,new g(".gallery-item").refresh()}function q(){const r=document.querySelector(".galleriesBox");r.innerHTML=""}const b=document.querySelector(".search-form"),w=document.querySelector(".search-data");document.querySelector(".galleriesBox");let i=1;const p=15;let d="";b.addEventListener("submit",B);function B(r){r.preventDefault();const o=w.value.trim();if(!o){s.error({title:"Error",message:"Please, enter a search query"});return}q(),i=1,d=o,v(),c(o).then(t=>{t.hits.length===0?s.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again."}):(u(t.hits),t.hits.length<p?m():E(),f())}).catch(t=>{s.error({position:"topRight",message:"Error"})}).finally(()=>{y()})}function v(){document.querySelector(".loader").style.display="block"}function y(){document.querySelector(".loader").style.display="none"}function f(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}document.querySelector(".galleryBtn").addEventListener("click",()=>{P()});function E(){document.querySelector(".galleryBtn").style.display==="none"&&(document.querySelector(".galleryBtn").style.display="block")}function m(){document.querySelector(".galleryBtn").style.display="none"}function P(){c(d,i).then(r=>{r.hits.length===0||i>=r.totalHits/p?(m(),s.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(u(r.hits),i++,f())}).catch(r=>{s.error({position:"topRight",message:"Error"})}).finally(()=>{y()})}
//# sourceMappingURL=commonHelpers.js.map
