import{a as h,S as g,i}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const S="44094007-67477d06fc63ea0136e02e71a",L="https://pixabay.com/api/";async function c(e,o){try{return(await h.get(L,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:"15"}})).data}catch(t){throw console.error("Error fetching images:",t),t}}function u(e){const o=document.querySelector(".galleriesBox"),t=e.map(s=>`
      <a class="gallery-item" href="${s.largeImageURL}">
        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${s.likes}</p>
          <p class="info-item"><span>Views:</span> ${s.views}</p>
          <p class="info-item"><span>Comments:</span> ${s.comments}</p>
          <p class="info-item"><span>Downloads:</span> ${s.downloads}</p>
        </div>
      </a>`).join("");o.insertAdjacentHTML("beforeend",t),b.refresh()}function q(){const e=document.querySelector(".galleriesBox");e.innerHTML=""}const b=new g(".gallery-item"),w=document.querySelector(".search-form"),B=document.querySelector(".search-data");document.querySelector(".galleriesBox");let l=1;const d=15;let p="";w.addEventListener("submit",v);function v(e){e.preventDefault();const o=B.value.trim();if(!o){i.error({title:"Error",message:"Please, enter a search query"});return}q(),l=1,p=o,E(),c(o).then(t=>{t.hits.length===0?i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again."}):(u(t.hits),t.hits.length<d?m():P(),f())}).catch(t=>{i.error({position:"topRight",message:"Error"})}).finally(()=>{y()})}function E(){document.querySelector(".loader").style.display="block"}function y(){document.querySelector(".loader").style.display="none"}function f(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}document.querySelector(".galleryBtn").addEventListener("click",()=>{R()});function P(){document.querySelector(".galleryBtn").style.display==="none"&&(document.querySelector(".galleryBtn").style.display="block")}function m(){document.querySelector(".galleryBtn").style.display="none"}function R(){c(p,l).then(e=>{e.hits.length===0||l>=e.totalHits/d?(m(),i.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(u(e.hits),l++,f())}).catch(e=>{i.error({position:"topRight",message:"Error"})}).finally(()=>{y()})}
//# sourceMappingURL=commonHelpers.js.map
